-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: PF.CONTRACT
-- Reason: test message

INSERT INTO PF.CONTRACT (id, product_id, customer_id, company_id, start_date, maturity_date) VALUES (1, 'ук', 'уцк', 'ы', 'у', 'вы');