-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: CURRENCY
-- Reason: загрузка USD валюты в систему

INSERT INTO CURRENCY (id, numeric_code, no_of_decimals, quotation_code, ccy_name, precious_metal, decimals_name, base_ccy_rank, interest_day_basis, country_code) VALUES ('USD', 840, 2, 0, 'US Dollar', 0, 'Cent', 1, 'A366/360', 'US');