-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: currency.CURRENCY
-- Reason: 6uggiu

ALTER TABLE "currency"."CURRENCY" ADD COLUMN "question" business_types.Enum;
COMMENT ON COLUMN "currency"."CURRENCY"."question" IS 'business_type:ENUM(TO BE | NOT TO BE)';