-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: new-epic.table.for.demo
-- Reason: amend table structure for Demo

ALTER TABLE "new-epic"."table.for.demo" ALTER COLUMN "ccy" TYPE business_types.Alphanumeric USING "ccy"::business_types.Alphanumeric;
ALTER TABLE "new-epic"."table.for.demo" ALTER COLUMN "ccy" SET DEFAULT 'USD';
ALTER TABLE "new-epic"."table.for.demo" DROP COLUMN "isactive";
ALTER TABLE "new-epic"."table.for.demo" ADD COLUMN "new_field" business_types.Period;