-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: demo-epic.table.for.demo
-- Reason: gfdsg

CREATE SCHEMA IF NOT EXISTS "demo-epic";

CREATE TABLE "demo-epic"."table.for.demo" (
    id business_types.Id PRIMARY KEY,
    fff business_types.Amount,
    ffsdfds business_types.Enum
);

COMMENT ON COLUMN "demo-epic"."table.for.demo"."id" IS 'business_type:ID';
COMMENT ON COLUMN "demo-epic"."table.for.demo"."fff" IS 'business_type:AMOUNT(USD)';
COMMENT ON COLUMN "demo-epic"."table.for.demo"."ffsdfds" IS 'business_type:ENUM(ACTIVE | DORMANT)';

ALTER TABLE "demo-epic"."table.for.demo" ENABLE ROW LEVEL SECURITY;