-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test
-- Reason: test 35463

CREATE TABLE test (
    id business_types.ID PRIMARY KEY,
    field business_types.Amount DEFAULT 0
);