-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: public.FUNDS.TRANSFER
-- Reason: тест обновление структуры таблицы

ALTER TABLE "public"."FUNDS.TRANSFER" ALTER COLUMN "credit_account" TYPE business_types.Numeric USING "credit_account"::business_types.Numeric;
ALTER TABLE "public"."FUNDS.TRANSFER" ALTER COLUMN "credit_account" DROP NOT NULL;
ALTER TABLE "public"."FUNDS.TRANSFER" ALTER COLUMN "transaction_amount" SET DEFAULT 10;