-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: my-demo-epic.table.for.demo
-- Reason: added new TABLE for Demo

CREATE SCHEMA IF NOT EXISTS "my-demo-epic";

CREATE TABLE "my-demo-epic"."table.for.demo" (
    id business_types.Id PRIMARY KEY,
    statuses business_types.Enum,
    usr_statuses business_types.VirtualTable,
    amt business_types.Amount NOT NULL,
    ccy business_types.LinkedTable NOT NULL,
    narrative business_types.MultilanguageText
);

COMMENT ON COLUMN "my-demo-epic"."table.for.demo"."id" IS 'business_type:ID';
COMMENT ON COLUMN "my-demo-epic"."table.for.demo"."statuses" IS 'business_type:ENUM(Opened | Closed)';
COMMENT ON COLUMN "my-demo-epic"."table.for.demo"."usr_statuses" IS 'business_type:VIRTUALTABLE(BankCustomStatuses)';
COMMENT ON COLUMN "my-demo-epic"."table.for.demo"."amt" IS 'business_type:AMOUNT(USD)';
COMMENT ON COLUMN "my-demo-epic"."table.for.demo"."ccy" IS 'business_type:LINKEDTABLE(currency.CURRENCY)';
COMMENT ON COLUMN "my-demo-epic"."table.for.demo"."narrative" IS 'business_type:MULTILANGUAGETEXT';

ALTER TABLE "my-demo-epic"."table.for.demo" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access" ON "my-demo-epic"."table.for.demo" FOR ALL USING (true) WITH CHECK (true);