-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: PF.CONTRACT
-- Reason: ep test

INSERT INTO PF.CONTRACT (id, product_id, customer_id, company_id, start_date, maturity_date) VALUES (1, '"342"', '"345"', '"GB0010001"', 20260101, 20280101);