-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: demo.demo
-- Reason: ddd

CREATE SCHEMA IF NOT EXISTS "demo";

CREATE TABLE "demo"."demo" (
    id business_types.Id PRIMARY KEY,
    ddd business_types.Boolean
);

COMMENT ON COLUMN "demo"."demo"."id" IS 'business_type:ID';
COMMENT ON COLUMN "demo"."demo"."ddd" IS 'business_type:BOOLEAN';

ALTER TABLE "demo"."demo" ENABLE ROW LEVEL SECURITY;