-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: PF.CONTRACT
-- Reason: ep01.02 DSGJKLDJG

INSERT INTO PF.CONTRACT (id, product_id, customer_id, company_id, start_date, maturity_date) VALUES (1, 'HDSFH', 'FJSL', 'DSF', 'DFJJ', 'DSF');