-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test-group.test.table
-- Reason: hgk

ALTER TABLE "test-group"."test.table" ALTER COLUMN "id" TYPE business_types.business_types.id USING "id"::business_types.business_types.id;
ALTER TABLE "test-group"."test.table" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "test-group"."test.table" ADD COLUMN "amt" business_types.business_types.amount;
ALTER TABLE "test-group"."test.table" ADD COLUMN "ccy" business_types.business_types.linkedtable DEFAULT 'XOF';
ALTER TABLE "test-group"."test.table" ADD COLUMN "isactive" business_types.business_types.boolean DEFAULT true;