-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: PF.CONTRACT
-- Reason: ep-04.XX product uploaded

INSERT INTO PF.CONTRACT (id, product_id, customer_id, company_id, start_date, maturity_date) VALUES (1, 12345, 1000, 'GB0010001', 20260101, 20280101);