-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: public.test.3.extra
-- Reason: new test.3 table

CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "public"."test.3.extra" (
    amt business_types.Amount NOT NULL,
    value_date business_types.Date,
    desc business_types.Any,
    ccy business_types.LinkedTable DEFAULT 'USD'
);