-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: PF.PRODUCT
-- Reason: nc,mxzn.vzx

UPDATE PF.PRODUCT SET base_currency = 'XYZA' WHERE id = '1';
UPDATE PF.PRODUCT SET description = '{en=DESC}', interest_rate = 3.4 WHERE id = '2';