-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test
-- Reason: TEDFSKLHFDLS;

CREATE TABLE test (
    id ID PRIMARY KEY,
    abcd business_types.Period DEFAULT 1Y,
    amt business_types.Amount DEFAULT 0
);