-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test.2
-- Reason: new table test.2

CREATE SCHEMA IF NOT EXISTS "test";

CREATE TABLE "test"."2" (
    deb.amt business_types.Amount NOT NULL,
    deb.ccy business_types.LinkedTable NOT NULL DEFAULT 'USD',
    cred.amt business_types.Amount NOT NULL,
    cred.ccy business_types.LinkedTable NOT NULL DEFAULT 'USD',
    date business_types.Date NOT NULL,
    narrative business_types.Any
);