-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test-group.test.table
-- Reason: 5787

ALTER TABLE "test-group"."test.table" ALTER COLUMN "id" TYPE business_types.ID USING "id"::business_types.ID;
ALTER TABLE "test-group"."test.table" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "test-group"."test.table" ADD COLUMN "amt" business_types.Amount;
ALTER TABLE "test-group"."test.table" ADD COLUMN "ccy" business_types.LinkedTable DEFAULT 'XOF';
ALTER TABLE "test-group"."test.table" ADD COLUMN "isactive" business_types.Boolean DEFAULT true;