-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: new-epic.table.for.demo
-- Reason: new table for Demo

CREATE SCHEMA IF NOT EXISTS "new-epic";

CREATE TABLE "new-epic"."table.for.demo" (
    id business_types.ID PRIMARY KEY,
    amt business_types.Amount NOT NULL,
    ccy business_types.LinkedTable NOT NULL DEFAULT 'XOF',
    isactive business_types.Boolean DEFAULT true,
    narrative business_types.MultilanguageText
);
ALTER TABLE "new-epic"."table.for.demo" ENABLE ROW LEVEL SECURITY;