-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: currency.CURRENCY
-- Reason: EP-01... Currency TABLE updated

ALTER TABLE "currency"."CURRENCY" ALTER COLUMN "numeric_code" SET NOT NULL;
ALTER TABLE "currency"."CURRENCY" DROP COLUMN "demo_field";
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "descr_demo" business_types.MultilanguageText;
COMMENT ON COLUMN "currency"."CURRENCY"."descr_demo" IS 'business_type:MULTILANGUAGETEXT';