-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test
-- Reason: test update table

CREATE TABLE "test" (
    id business_types.ID PRIMARY KEY,
    field business_types.Time,
    field2 business_types.Amount NOT NULL DEFAULT 0
);