-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: demo-epic.table.for.demo
-- Reason: new table creation for Demo

CREATE SCHEMA IF NOT EXISTS "demo-epic";

CREATE TABLE "demo-epic"."table.for.demo" (
    id business_types.Id PRIMARY KEY,
    amt business_types.Amount NOT NULL,
    ccy business_types.LinkedTable NOT NULL,
    isactive business_types.Boolean,
    status business_types.Enum
);

COMMENT ON COLUMN "demo-epic"."table.for.demo"."id" IS 'business_type:ID';
COMMENT ON COLUMN "demo-epic"."table.for.demo"."amt" IS 'business_type:AMOUNT(USD)';
COMMENT ON COLUMN "demo-epic"."table.for.demo"."ccy" IS 'business_type:LINKEDTABLE';
COMMENT ON COLUMN "demo-epic"."table.for.demo"."isactive" IS 'business_type:BOOLEAN';
COMMENT ON COLUMN "demo-epic"."table.for.demo"."status" IS 'business_type:ENUM(OPENED | CLOSED)';

ALTER TABLE "demo-epic"."table.for.demo" ENABLE ROW LEVEL SECURITY;