-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: currency.CURRENCY
-- Reason: the table CURRENCY updated (new field added)

ALTER TABLE "currency"."CURRENCY" ALTER COLUMN "numeric_code" TYPE business_types.Numeric USING "numeric_code"::business_types.Numeric;
COMMENT ON COLUMN "currency"."CURRENCY"."numeric_code" IS 'business_type:NUMERIC';
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "demo_field" business_types.Enum;
COMMENT ON COLUMN "currency"."CURRENCY"."demo_field" IS 'business_type:ENUM(YES | NO | MAYBE)';