-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: currency.CURRENCY
-- Reason: CCY structure

ALTER TABLE "currency"."CURRENCY" ADD COLUMN "numeric_code" business_types.Enum;
COMMENT ON COLUMN "currency"."CURRENCY"."numeric_code" IS 'business_type:ENUM';
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "no_of_decimals" business_types.Numeric;
COMMENT ON COLUMN "currency"."CURRENCY"."no_of_decimals" IS 'business_type:NUMERIC';
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "quotation_code" business_types.Numeric;
COMMENT ON COLUMN "currency"."CURRENCY"."quotation_code" IS 'business_type:NUMERIC';
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "interest_day_basis" business_types.LinkedTable;
COMMENT ON COLUMN "currency"."CURRENCY"."interest_day_basis" IS 'business_type:LINKEDTABLE(INTEREST.BASIS)';
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "base_ccy_rank" business_types.Numeric;
COMMENT ON COLUMN "currency"."CURRENCY"."base_ccy_rank" IS 'business_type:NUMERIC';
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "precious_metal" business_types.Boolean;
COMMENT ON COLUMN "currency"."CURRENCY"."precious_metal" IS 'business_type:BOOLEAN';
ALTER TABLE "currency"."CURRENCY" ADD COLUMN "decimals_name" business_types.MultilanguageText;
COMMENT ON COLUMN "currency"."CURRENCY"."decimals_name" IS 'business_type:MULTILANGUAGETEXT';