-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test
-- Reason: test new table

CREATE TABLE test (
    id ID PRIMARY KEY,
    field business_types.Date DEFAULT 20260101
);