-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test-group.test.table
-- Reason: 5547657

ALTER TABLE "test-group"."test.table" DROP COLUMN "flag";
ALTER TABLE "test-group"."test.table" DROP COLUMN "isactive";
ALTER TABLE "test-group"."test.table" ADD COLUMN "isactive2" business_types.boolean DEFAULT true;
ALTER TABLE "test-group"."test.table" ADD COLUMN "narrative" business_types.Any;