-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: account-restrictions.AM.POSTING.RESTRICT
-- Reason: rytyiu

ALTER TABLE "account-restrictions"."AM.POSTING.RESTRICT" ALTER COLUMN "id" TYPE business_types.ID USING "id"::business_types.ID;
ALTER TABLE "account-restrictions"."AM.POSTING.RESTRICT" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "account-restrictions"."AM.POSTING.RESTRICT" ADD COLUMN "field1" business_types.Alphanumeric;