-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: public.test.5
-- Reason: new table for demo

CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "public"."test.5" (
    id business_types.Id PRIMARY KEY,
    amount business_types.Amount NOT NULL,
    value_date business_types.Date,
    ccy business_types.LinkedTable NOT NULL DEFAULT 'EUR',
    narrative business_types.Any
);
ALTER TABLE "public"."test.5" ENABLE ROW LEVEL SECURITY;