-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: public.suo
-- Reason: tyu

CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "public"."suo" (
    id business_types.business_types.Id PRIMARY KEY,
    ma business_types.Numeric DEFAULT 1
);
ALTER TABLE "public"."suo" ENABLE ROW LEVEL SECURITY;