-- DDL Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: test-group.test.table
-- Reason: testing

CREATE SCHEMA IF NOT EXISTS "test-group";

CREATE TABLE "test-group"."test.table" (
    id business_types.ID PRIMARY KEY,
    amt business_types.Amount,
    ccy business_types.LinkedTable DEFAULT 'XOF'
);
ALTER TABLE "test-group"."test.table" ENABLE ROW LEVEL SECURITY;