DELETE FROM "currency"."CURRENCY" WHERE "id" = 'USD';
INSERT INTO "currency"."CURRENCY" ("id", "NUMERIC_CODE", "NO_OF_DECIMALS") VALUES ('XOF', 734, 0);
UPDATE "currency"."CURRENCY" SET "NUMERIC_CODE" = 974, "NO_OF_DECIMALS" = 2 WHERE "id" = 'EUR';