-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: product

UPDATE product SET status = 'ACTIVEd' WHERE product_code = 'SAVINGS_PREMIUM';
UPDATE product SET name = 'VIP Product' WHERE product_code = 'SAVINGS_STD';
DELETE FROM product WHERE product_code = 'CURRENT';