CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code text NOT NULL UNIQUE,
    name text NOT NULL,
    type text NOT NULL,
    status text NOT NULL,
    currency text NOT NULL
);

-- Вставляем baseline данные (имитация того, что уже есть в проде)
INSERT INTO product (product_code, name, type, status, currency) VALUES 
('SAVINGS_STD', 'Standard Savings', 'SAVINGS', 'ACTIVE', 'XAF'),
('CURRENT_STD', 'Standard Current', 'CURRENT', 'ACTIVE', 'XAF');