-- Migration generated by Model Bank Manager
-- Author: anton.karachun@innowise.com
-- Table: product

UPDATE product SET name = 'Test 2' WHERE product_code = 'CURRENT';
INSERT INTO product (id, product_code, name, type, status, currency) VALUES (5, 'VIP', 'VIP Product Savings', 'SAVINGS', 'ACTIVE', 'USD');