-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: product

UPDATE product SET status = 'SUSPENDED' WHERE product_code = 'SAVINGS_PREMIUM';
UPDATE product SET type = 'CURRENT', status = 'ACTIVE' WHERE product_code = 'SAVINGS_STD';
INSERT INTO product (id, product_code, name, type, status, currency) VALUES (2, 'VIP VIC Product', 'Wei dzia', 'SAVINGS', 'SUSPENDED', 'GBP');
DELETE FROM product WHERE product_code = 'VIP';