-- Migration generated by Model Bank Manager
-- Author: andrei.sech@innowise.com
-- Table: product

UPDATE product SET name = 'Premium Savings' WHERE product_code = 'SAVINGS_PREMIUM';
UPDATE product SET name = 'Standard Savings Product' WHERE product_code = 'SAVINGS_STD';
INSERT INTO product (id, product_code, name, type, status, currency) VALUES (4, 'CURRENT', 'Test', 'SAVINGS', 'SUSPENDED', 'XAF');
DELETE FROM product WHERE product_code = 'CURRENT_STD';