name: Deploy SQL Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/*.sql'

jobs:
  apply-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Get changed SQL files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: migrations/*.sql

      - name: Run SQL in Supabase
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          DB_PASS: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          # Динамически собираем URL из твоих секретов
          SUPABASE_DB_URL="postgresql://postgres:${DB_PASS}@db.${PROJECT_ID}.supabase.co:5432/postgres"
          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "🚀 Выполняем скрипт: $file"
            psql "$SUPABASE_DB_URL" -f "$file"
          done